name: yofa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.3
  internet_connection_checker: ^3.0.1
  lottie: ^3.1.3
  flutter_local_notifications: ^18.0.1
  rxdart: ^0.27.7
  google_mobile_ads: ^5.2.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  device_info_plus: ^11.3.0
  encrypt: ^5.0.3
  typewritertext: ^3.0.9
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/play_store_512_new.png"
  min_sdk_android: 21  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
